# Generated by Django 3.2.8 on 2022-02-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scripture',
            fields=[
                ('scripture_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(default='text', max_length=500, verbose_name='Words')),
                ('scripture', models.CharField(default='scripture', max_length=50, verbose_name='Scripture')),
                ('favorite', models.BooleanField(default=False)),
                ('encouragement', models.BooleanField(default=False)),
                ('testimony', models.BooleanField(default=False)),
                ('low', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'scripture',
            },
        ),
    ]
