# Generated by Django 3.2.8 on 2022-02-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripture',
            name='tip',
            field=models.CharField(default='When your...', max_length=100, verbose_name='Tip'),
        ),
    ]
